// Code generated by MockGen. DO NOT EDIT.
// Source: ../client_validator.go

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	dal "github.com/reecerussell/goidc/dal"
	reflect "reflect"
)

// MockClientValidator is a mock of ClientValidator interface.
type MockClientValidator struct {
	ctrl     *gomock.Controller
	recorder *MockClientValidatorMockRecorder
}

// MockClientValidatorMockRecorder is the mock recorder for MockClientValidator.
type MockClientValidatorMockRecorder struct {
	mock *MockClientValidator
}

// NewMockClientValidator creates a new mock instance.
func NewMockClientValidator(ctrl *gomock.Controller) *MockClientValidator {
	mock := &MockClientValidator{ctrl: ctrl}
	mock.recorder = &MockClientValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientValidator) EXPECT() *MockClientValidatorMockRecorder {
	return m.recorder
}

// ValidateTokenRequest mocks base method.
func (m *MockClientValidator) ValidateTokenRequest(c *dal.Client, secret, grantType string, scopes []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateTokenRequest", c, secret, grantType, scopes)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateTokenRequest indicates an expected call of ValidateTokenRequest.
func (mr *MockClientValidatorMockRecorder) ValidateTokenRequest(c, secret, grantType, scopes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateTokenRequest", reflect.TypeOf((*MockClientValidator)(nil).ValidateTokenRequest), c, secret, grantType, scopes)
}

// ValidateLoginRequest mocks base method.
func (m *MockClientValidator) ValidateLoginRequest(c *dal.Client, redirectUri string, scopes []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateLoginRequest", c, redirectUri, scopes)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateLoginRequest indicates an expected call of ValidateLoginRequest.
func (mr *MockClientValidatorMockRecorder) ValidateLoginRequest(c, redirectUri, scopes interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateLoginRequest", reflect.TypeOf((*MockClientValidator)(nil).ValidateLoginRequest), c, redirectUri, scopes)
}
