name: Authorize UI Handler

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "**.go"
  pull_request:
    branches:
      - "master"
    paths:
      - "**.go"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: |
          chmod +x ./scripts/build.sh
          ./scripts/build.sh
        env:
          NAME: authorize-ui
          VERSION: ${{ github.run_id }}
          WORKING_DIRECTORY: cmd/authorize-ui

      - name: Archive Build Artifacts
        if: (github.ref == 'ref/heads/master' && github.event_name == 'push') || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: cmd/authorize-ui/authorize-ui.${{github.run_id}}.zip
      
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: |
          go test ./...
          cd cmd/authorize-ui
          go test
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          UI_BUCKET: goidc-authorize-ui

  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: (github.ref == 'ref/heads/master' && github.event_name == 'push') || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: dist/

      - name: Upload To S3
        run: |
          chmod +x ./scripts/publish.sh
          ./scripts/publish.sh
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          FILE: dist/authorize-ui.${{github.run_id}}.zip
          S3_BUCKET: ${{ secrets.S3_SOURCE_BUCKET }}
          S3_KEY: authorize-ui/${{github.run_id}}.zip

  deployDev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    if: (github.ref == 'ref/heads/master' && github.event_name == 'push') || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    needs: publish
    environment: Dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          chmod +x ./scripts/deploy.sh
          ./scripts/deploy.sh
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.S3_SOURCE_BUCKET }}
          SOURCE_ZIP: authorize-ui/${{github.run_id}}.zip
          NAME: authorize-ui
          ENV: dev

  deployTest:
    name: Deploy Test
    runs-on: ubuntu-latest
    if: (github.ref == 'ref/heads/master' && github.event_name == 'push') || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    needs: publish
    environment: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          chmod +x ./scripts/deploy.sh
          ./scripts/deploy.sh
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.S3_SOURCE_BUCKET }}
          SOURCE_ZIP: authorize-ui/${{github.run_id}}.zip
          NAME: authorize-ui
          ENV: test

  deployProd:
    name: Deploy Prod
    runs-on: ubuntu-latest
    if: (github.ref == 'ref/heads/master' && github.event_name == 'push') || github.event_name == 'workflow_dispatch'
    needs: publish
    environment: Prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          chmod +x ./scripts/deploy.sh
          ./scripts/deploy.sh
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET: ${{ secrets.S3_SOURCE_BUCKET }}
          SOURCE_ZIP: authorize-ui/${{github.run_id}}.zip
          NAME: authorize-ui
          ENV: prod
