name: Create User

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "cmd/create-user/**.go"
  pull_request:
    branches:
      - "master"
    paths:
      - "cmd/create-user/**.go"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: ./scripts/build.sh
        env:
          NAME: create-user
          VERSION: ${{ github.run_id }}
          WORKING_DIRECTORY: cmd/create-user

      - name: Archive Build Artifacts
        if: (github.ref == 'ref/heads/master' && github.event_name == 'push') || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: cmd/create-user/build.zip
      
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: |
          go test ./...
          cd cmd/create-user
          go test
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: (github.ref == 'ref/heads/master' && github.event_name == 'push') || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Build Artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: dist/

      - name: Upload To S3
        run: ./scripts/publish.sh
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          FILE: dist/build.zip
          S3_BUCKET: ${{ secrets.S3_SOURCE_BUCKET }}
          S3_KEY: create-user/${{github.run_id}}.zip
          NAME: goidc-create-user

  deployDev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    if: (github.ref == 'ref/heads/master' && github.event_name == 'push') || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    needs: publish
    environment: Dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        run: ./scripts/deploy_api.sh
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          DESCRIPTION: "Deploy Function goidc-create-user (${{github.run_id}})"
          STAGE: dev

  deployTest:
    name: Deploy Test
    runs-on: ubuntu-latest
    if: (github.ref == 'ref/heads/master' && github.event_name == 'push') || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
    needs: publish
    environment: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        run: ./scripts/deploy_api.sh
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          DESCRIPTION: "Deploy Function goidc-create-user (${{github.run_id}})"
          STAGE: test

  deployProd:
    name: Deploy Prod
    runs-on: ubuntu-latest
    if: (github.ref == 'ref/heads/master' && github.event_name == 'push') || github.event_name == 'workflow_dispatch'
    needs: publish
    environment: Prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        run: ./scripts/deploy_api.sh
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          DESCRIPTION: "Deploy Function goidc-create-user (${{github.run_id}})"
          STAGE: prod
