name: e2e

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    paths:
      - "**.go"
  pull_request:
    branches:
      - "master"
    paths:
      - "**.go"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
    
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: |
          cd e2e
          go test ./...
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          CLIENTS_TABLE_NAME: goidc-clients-test
          BASE_API_URL: ${{ secrets.BASE_API_URL }}